---
title: "p8105_hw6_qc2336"
author: "Qiran Chen"
output: github_document
date: "2023-11-28"
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
library(modelr)
```

## Problem 1

```{r}
homicide=read_csv("./data/homicide-data.csv")|>
  mutate(city_state=str_c(city,state,sep=", "))|>
  mutate(victim_age=as.numeric(victim_age),
          resolved= case_when(
      disposition == "Closed without arrest" ~ 0,
      disposition == "Open/No arrest"        ~ 0,
      disposition == "Closed by arrest"    ~ 1))|>
  filter(city_state !=c("Dallas, TX", "Phoenix, AZ","Kansas City, MO"))|>
        filter(city_state !="Tulsa, AL")|>
        filter(victim_race %in% c("White", "Black"))|>
  select(city_state, resolved, victim_age, victim_race, victim_sex)|>
    drop_na()


  
```


```{r}
case_baltimore=homicide|>
  filter(city_state %in% "Baltimore, MD")
glm(resolved~ victim_age + victim_race + victim_sex,
    data = case_baltimore,
    family = binomial())|>
  broom::tidy()|>
  mutate(OR = exp(estimate),
         OR_lower = exp(estimate - 1.96*std.error),
         OR_upper = exp(estimate + 1.96*std.error) ) |>
  filter(term %in% c('victim_sexMale')) |>
  select(estimate, OR,OR_lower,OR_upper) 
  
```
```{r}
case_all=homicide|>
  group_by(city_state)|>
  nest() |>
  mutate(
    model = map(data, ~ glm(resolved ~ victim_age + victim_sex + victim_race, data = .x, family = binomial())),
    tidy_results = map(model, broom::tidy),
    filtered_results = map(tidy_results, ~ filter(.x, term == "victim_sexMale"))
  ) |>
  unnest(filtered_results) |>
  mutate(OR = exp(estimate),
         OR_lower = exp(estimate - 1.96*std.error),
         OR_upper = exp(estimate + 1.96*std.error))|>
  select(city_state, OR, OR_lower, OR_upper)

case_all
  
```

```{r}
case_all|>
  ggplot(aes(x=city_state,y=OR))+
  geom_point()+
  geom_errorbar(aes(ymin=OR_lower,ymax=OR_upper))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
  
```


## Problem 2

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r}
lm(tmax~ tmin+prcp, data=weather_df)
```
```{r}
bootstrap_rsquare = 
  weather_df |> 
  bootstrap(5000) |>
  mutate(fit = map(.x = strap, ~lm(tmax ~ tmin+prcp, data = .x))) |>
    mutate(rsquare = map(fit, broom::glance))|>
  unnest(rsquare, names_sep = NULL)|>
  select(.id, r.squared)
  
```

```{r}
bootstrap_rsquare|>
  ggplot(aes(x = r.squared)) + geom_density()


bootstrap_rsquare|>
  summarize(r_squared_lower = quantile(r.squared, 0.025),
  r_squared_upper = quantile(r.squared, 0.975))
                      
```


```{r}
bootstraps_log = 
  weather_df |> 
  bootstrap(5000) |>
  mutate(fit = map(.x = strap, ~lm(tmax ~ tmin+prcp, data = .x))) |>
  mutate(logvalue = map(fit, broom::tidy))|>
    unnest(logvalue) |>
    select(.id,term,estimate)|>
  pivot_wider(
    names_from = term,
    values_from = estimate) |>
  rename(
    beta_0 = `(Intercept)`,
    beta_1 = tmin) |>
  mutate(log_b0xb1 = log(beta_0*beta_1)) |>
  select( log_b0xb1)

bootstraps_log|>
    ggplot(aes(x = log_b0xb1)) +
    geom_density()

```

```{r}
bootstraps_log|>
  summarize(log_lower = quantile(log_b0xb1, 0.025),
  log_upper = quantile(log_b0xb1, 0.975))
                      
```

## Problem 3

```{r}
birthweight=read_csv("./data/birthweight.csv")
```
```{r}
head(birthweight)
```

```{r}
birthweight=birthweight|>
  mutate(malform=factor(malform),
         mrace=factor(mrace),
         frace=factor(frace),
         babysex=factor(babysex))|>
  drop_na()


birthweight
```

```{r}
model1=lm(bwt ~gaweeks+malform+smoken+mrace, data = birthweight)
  
  
broom::tidy(model1)

birthweight|>
  add_predictions(model1)|> 
  add_residuals(model1)|>
  ggplot(aes(x=pred,y=resid))+geom_point()
```
```{r}
cv = 
  crossv_mc(birthweight, 100) |>
  mutate(
    train = map(train, as_tibble), 
    test = map(test, as_tibble))

```


```{r}
cv=cv|>
  mutate(
    model_1 = map(train, ~lm(bwt ~gaweeks+malform+smoken+mrace, data = birthweight), data = .x),
    model_2  = map(train, ~lm(bwt ~ gaweeks + blength, data = .x)),
    model_3  = map(train, ~lm(bwt ~ bhead*blength*babysex, data = .x))) |>
  mutate(
    rmse_1 = map2_dbl(model_1, test, ~rmse(model = .x, data = .y)),
    rmse_2 = map2_dbl(model_2, test, ~rmse(model = .x, data = .y)),
    rmse_3 = map2_dbl(model_3, test, ~rmse(model = .x, data = .y)))

cv |> 
  select(starts_with("rmse")) |> 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") |> 
  mutate(model = fct_inorder(model)) |> 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```
>> From the model, model 3 is the best, since it has the lowest rmse.
